version: v1.0
author: lhlyu
name: iyu
env: prod

jwt:
  secret: 3.14159265358979323

server:
  host: localhost
  port: 8080
  limit: 5   # 每秒最多允许五个请求

log:
  level: debug
  timeFormat: 2006-01-02 15:04:05
  outFile:          # 输出文件
  outWay: normal    # normal  /  json

redis:
  addr: 127.0.0.1:6379
  password: 123456
  database: 0
  maxActive: 50
  idleTimeout: 60

redis_key:
  iyu: IYU
  tag: "IYU:TAG"
  nail: "IYU:NAIL"
  category: "IYU:CATEGORY"
  quanta: "IYU:QUANTA"

db:
  db_wr:
    user: root
    password:
    host: 127.0.0.1
    port: 3306
    database: lhlyu_blog
    charset: utf8
    parseTime: true
    maxOpenConns: 1
    maxIdleConns: 3
    connMaxLifetime: 30

email:
  host: smtp.163.com
  port: 465
  user: 名字
  password: SMTP邮箱密码
  from: 负责发送消息的邮箱
  to: 接收消息的邮箱
  subject: 标题
